document ldap permissions configuration
kadai-io/kadai-doc pull request #37
Opened 2024-12-06 14:18 UTC by ryzheboka

2024-12-16 08:53 UTC, holgerhagen requested changes

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.userSearchBase                               | The base dn of each use.
The search root for users

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.userFirstnameAttribute                       | Name of the attribute that is used to specify the first name of the user in the ldif file.
please remove the part with the ldif file in all entries. ldif is just a data structure to import/export LDAP structures.

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.groupSearchBase                              | The base dn of each group
The search root for groups

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.groupNameAttribute                           | Name of the attribute that is used to specify the name of the group in the ldif file.
see above

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.minSearchForLength<br /> (optional)          |
We do need the break (<br/>) for formatting?

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.permissionSearchBase <br />(optional)        | The base dn of each permission
The search root for permissions

2024-12-16 08:53 UTC, holgerhagen commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.groupsOfUser.type<br />(optional)            | Type of the attribute in a group object, which specifies the member of the group.If you specify ‘dn’ as the type, KADAI assumes that this f
I don't remember the background of this. Do some customers use other values than dn? At least we should specify what the options of type are. Or is it just 'dn' or empty?

2025-01-03 08:52 UTC, ryzheboka commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.minSearchForLength<br /> (optional)          |
Yes

2025-01-03 09:14 UTC, ryzheboka commented on docs/user-guide/configuration/ldap.md
> +| kadai.ldap.groupsOfUser.type<br />(optional)            | Type of the attribute in a group object, which specifies the member of the group.If you specify ‘dn’ as the type, KADAI assumes that this f
I am not aware that any of our customers use other values than dn. Should we discuss this? Alternatevely, I can just add that it should be "dn" or empty, if we both agree on that.

The code only differentiates between "dn" and all other values, so it looks like it's not intended to have values other than dn or empty. The only implemented usage of this field is in the context of searching groups that a specified accessId is member of. In this case, the dn of the user with the specified access id is looked up. However, if the value of the attribute is not "dn", the specified accessId is additionaly used for the search

2025-01-03 12:58 UTC, holgerhagen approved these changes

2025-01-08 08:52 UTC, merged